// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_ELg2Yby_GIXhGfLjFNvrfQbDICgyk8',
    appId: '1:134846671691:web:dfbd8f35244d546c4216ce',
    messagingSenderId: '134846671691',
    projectId: 'cmsc198-c2845',
    authDomain: 'cmsc198-c2845.firebaseapp.com',
    databaseURL: 'https://cmsc198-c2845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmsc198-c2845.appspot.com',
    measurementId: 'G-48NZRSKD31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2wbMonUlknnMBWB8W1XYif5DIUDwbug',
    appId: '1:134846671691:android:f0f3be1e1acc00fc4216ce',
    messagingSenderId: '134846671691',
    projectId: 'cmsc198-c2845',
    databaseURL: 'https://cmsc198-c2845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmsc198-c2845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEWYybX-WE-lY95-nL2463Fwygg8vIjI',
    appId: '1:134846671691:ios:e50d5878a2dd4f3e4216ce',
    messagingSenderId: '134846671691',
    projectId: 'cmsc198-c2845',
    databaseURL: 'https://cmsc198-c2845-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmsc198-c2845.appspot.com',
    iosBundleId: 'com.giociudadano.cmsc198.cmsc198',
  );
}
